microservices:
  microservice:
    order-service:
      name: save-order
      uri: http://order-service/order/save
      
    payment-service:
      name: save-payment
      uri: http://payment-service/payment/save
