microservices:
  microservice:
    id: payment-service
      name: save-payment
      uri: http://payment-service/payment/save
    
    id: order-service
      name: save-payment
      uri: http://order-service/order/save
